version: 2.1
# following https://stackoverflow.com/questions/44773415/how-to-push-a-commit-to-github-from-a-circleci-build-using-a-personal-access-tok

jobs:
  2019ncov:
    machine: true
    steps:
      - run:
          name: clone code
          working_directory: ~/workdir
          command: |
            cd ~/workdir
            git clone git@github.com:datumorphism/2019-ncov.git
            cd 2019-ncov/
            git checkout gh-pages
      - run:
          name: fetch 2019-nCoV data
          working_directory: ~/workdir/2019ncov-cache
          command: |
            cd ~/workdir/2019-ncov/2019ncov-cache
            echo 'Data collection'
            curl 'http://ncov.nosensor.com:8080/api/' > 2019ncov_data_$(date +%s).json
            echo 'End 2019ncov data collection'
            echo 'get into repo folder'
            cd ~/workdir/2019-ncov
            git config credential.helper 'cache --timeout=120'
            git config user.email "hi@leima.is"
            git config user.name "Datumorphism Data Bot"
            git add .
            git commit -m "collect 2019-nCoV data"
            # Push quietly to prevent showing the token in log
            git push -q

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - gh-pages
    jobs:
      - 2019ncov
